# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(542, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.playAll = QtWidgets.QPushButton(self.centralwidget)
        self.playAll.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.playAll.setObjectName("playAll")
        self.tabla = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla.setGeometry(QtCore.QRect(10, 70, 521, 501))
        self.tabla.setObjectName("tabla")
        self.tabla.setColumnCount(5)
        self.tabla.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(4, item)
        self.tabla.horizontalHeader().setStretchLastSection(True)
        self.tabla.verticalHeader().setStretchLastSection(False)
        self.playThis = QtWidgets.QPushButton(self.centralwidget)
        self.playThis.setGeometry(QtCore.QRect(100, 20, 75, 23))
        self.playThis.setObjectName("playThis")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 20, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vocabulary"))
        self.playAll.setText(_translate("MainWindow", "Play All"))
        item = self.tabla.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "English"))
        item = self.tabla.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Spanish"))
        item = self.tabla.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Portuguese"))
        item = self.tabla.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Italian"))
        item = self.tabla.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "French"))
        self.playThis.setText(_translate("MainWindow", "Play only this"))
        self.pushButton.setText(_translate("MainWindow", "Stop"))
